// nios_system.v

// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module nios_system (
		input  wire        clk_clk,                                              //                                      clk.clk
		input  wire        reset_reset_n,                                        //                                    reset.reset_n
		input  wire        video_decoder_0_external_interface_TD_CLK27,          //       video_decoder_0_external_interface.TD_CLK27
		input  wire [7:0]  video_decoder_0_external_interface_TD_DATA,           //                                         .TD_DATA
		input  wire        video_decoder_0_external_interface_TD_HS,             //                                         .TD_HS
		input  wire        video_decoder_0_external_interface_TD_VS,             //                                         .TD_VS
		input  wire        video_decoder_0_external_interface_clk27_reset,       //                                         .clk27_reset
		output wire        video_decoder_0_external_interface_TD_RESET,          //                                         .TD_RESET
		output wire        video_decoder_0_external_interface_overflow_flag,     //                                         .overflow_flag
		output wire [31:0] video_dma_controller_0_avalon_dma_master_address,     // video_dma_controller_0_avalon_dma_master.address
		input  wire        video_dma_controller_0_avalon_dma_master_waitrequest, //                                         .waitrequest
		output wire        video_dma_controller_0_avalon_dma_master_write,       //                                         .write
		output wire [31:0] video_dma_controller_0_avalon_dma_master_writedata,   //                                         .writedata
		input  wire        video_stream_export                                   //                             video_stream.export
	);

	nios_system_video_decoder_0 video_decoder_0 (
		.clk                      (),                                                 //                   clk.clk
		.reset                    (),                                                 //                 reset.reset
		.stream_out_ready         (),                                                 // avalon_decoder_source.ready
		.stream_out_startofpacket (),                                                 //                      .startofpacket
		.stream_out_endofpacket   (),                                                 //                      .endofpacket
		.stream_out_valid         (),                                                 //                      .valid
		.stream_out_data          (),                                                 //                      .data
		.TD_CLK27                 (video_decoder_0_external_interface_TD_CLK27),      //    external_interface.export
		.TD_DATA                  (video_decoder_0_external_interface_TD_DATA),       //                      .export
		.TD_HS                    (video_decoder_0_external_interface_TD_HS),         //                      .export
		.TD_VS                    (video_decoder_0_external_interface_TD_VS),         //                      .export
		.clk27_reset              (video_decoder_0_external_interface_clk27_reset),   //                      .export
		.TD_RESET                 (video_decoder_0_external_interface_TD_RESET),      //                      .export
		.overflow_flag            (video_decoder_0_external_interface_overflow_flag)  //                      .export
	);

	nios_system_video_dma_controller_0 video_dma_controller_0 (
		.clk                  (),                                                     //                      clk.clk
		.reset                (),                                                     //                    reset.reset
		.stream_data          (),                                                     //          avalon_dma_sink.data
		.stream_startofpacket (),                                                     //                         .startofpacket
		.stream_endofpacket   (),                                                     //                         .endofpacket
		.stream_valid         (),                                                     //                         .valid
		.stream_ready         (),                                                     //                         .ready
		.slave_address        (),                                                     // avalon_dma_control_slave.address
		.slave_byteenable     (),                                                     //                         .byteenable
		.slave_read           (),                                                     //                         .read
		.slave_write          (),                                                     //                         .write
		.slave_writedata      (),                                                     //                         .writedata
		.slave_readdata       (),                                                     //                         .readdata
		.master_address       (video_dma_controller_0_avalon_dma_master_address),     //        avalon_dma_master.address
		.master_waitrequest   (video_dma_controller_0_avalon_dma_master_waitrequest), //                         .waitrequest
		.master_write         (video_dma_controller_0_avalon_dma_master_write),       //                         .write
		.master_writedata     (video_dma_controller_0_avalon_dma_master_writedata)    //                         .writedata
	);

	nios_system_video_stream_router_0 video_stream_router_0 (
		.clk                       (),                    //                         clk.clk
		.reset                     (),                    //                       reset.reset
		.stream_in_data_0          (),                    // avalon_stream_router_sink_0.data
		.stream_in_startofpacket_0 (),                    //                            .startofpacket
		.stream_in_endofpacket_0   (),                    //                            .endofpacket
		.stream_in_valid_0         (),                    //                            .valid
		.stream_in_ready_0         (),                    //                            .ready
		.stream_in_data_1          (),                    // avalon_stream_router_sink_1.data
		.stream_in_startofpacket_1 (),                    //                            .startofpacket
		.stream_in_endofpacket_1   (),                    //                            .endofpacket
		.stream_in_valid_1         (),                    //                            .valid
		.stream_in_ready_1         (),                    //                            .ready
		.stream_select             (video_stream_export), //          external_interface.export
		.stream_out_ready          (),                    // avalon_stream_router_source.ready
		.stream_out_data           (),                    //                            .data
		.stream_out_startofpacket  (),                    //                            .startofpacket
		.stream_out_endofpacket    (),                    //                            .endofpacket
		.stream_out_valid          ()                     //                            .valid
	);

endmodule
